services:
  mysql:
    image: 'mysql:8.0'
    restart: "no"
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-test}
      - MYSQL_DATABASE=${MYSQL_DB:-notification}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app}
    ports:
      - '3306:3306'
